# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    cypress-run:
      runs-on: windows-latest

      steps:
      # Install chrome beta
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: beta
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome:beta

          #https://www.lekoarts.de/garden/running-cypress-tests-with-github-actions-in-parallel
#https://medium.com/geekculture/automatically-run-cypress-tests-on-every-code-push-with-github-action-and-docker-f6f305632fc5
