# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: beta
    - run: chrome --version
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    # Install chrome version
    run: echo 'ho'
    # - run: npm install cypress
    # - run: npx cypress run --browser chrome --config video=false
    # - run: npx cypress run --browser edge --config video=false
    # - run: npx cypress run --browser firefox --config video=false