name: ios
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Run test
          run: npm run wdio-browserstack
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs