name: ios
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Install chrome beta
        # - uses: browser-actions/setup-chrome@latest
          # with:
          #   chrome-version: beta
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Enable safaridriver
          run: sudo safaridriver --enable
        - name: Install appium
          run: sudo npm -g install appium 
        - name: Install start-ios-simulator
          run: sudo npm install -g start-ios-simulator
        - name: start-ios-simulator
          run: start-ios-simulator
        - name: Run test
          run: npm run ios.browser
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs